version: '3.5'

services:
  nginxreloader:
    image: 'rwd1/nginx-autoreloader:latest'
    volumes:
      - '/var/run/docker.sock:/var/run/docker.sock:ro'
      - ./nginx:/etc/nginx:ro
    environment:
      - NGINXNAMEFILTER=${STACKNAME}_nginx-
  
  nginx-a:
    image: nginx:alpine
    ports:
      - 81:80
    volumes:
    - ./nginx/conf.d:/etc/nginx/conf.d:ro

  nginx-b:
    image: nginx:alpine
    ports:
      - 82:80
    volumes:
    - ./nginx/conf.d:/etc/nginx/conf.d:ro
            
